name: Build and Release
on: [push]
jobs:
  preview:
    name: Pulumi Preview
    if: github.ref != 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Download Artifacts
        uses: actions/download-artifact@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14.x
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.ACCESS_KEY }}
          aws-region: eu-west-1
          aws-secret-access-key: ${{ secrets.ACCESS_KEY_SECRET }}
      - run: yarn --cwd infra
      - uses: actions/setup-node@v2
      - run: yarn --cwd ui install
      - run: yarn --cwd infra ts-node build.ts
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
  up:
    name: Pulumi Up
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Download Artifacts
        uses: actions/download-artifact@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14.x
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.ACCESS_KEY }}
          aws-region: eu-west-1
          aws-secret-access-key: ${{ secrets.ACCESS_KEY_SECRET }}
      - run: yarn --cwd infra
      - uses: pulumi/actions@v3
        with:
          command: up
          stack-name: verygoodsoftware/dev
          work-dir: infra
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}