name: Build and Release
on: [push]
jobs:
  buildJs:
    name: Build JavaScript
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Build Node
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: yarn --cwd ui install
      - run: yarn --cwd ui build
      - name: Upload Output
        uses: actions/upload-artifact@v2
        with:
          name: artifacts
          path: ui/build
  preview:
    name: Pulumi Preview
    if: github.ref != 'refs/heads/main'
    runs-on: ubuntu-latest
    needs:
      - buildJs
    steps:
      - uses: actions/checkout@v2
      - name: Download Artifacts
        uses: actions/download-artifact@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14.x
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.ACCESS_KEY }}
          aws-region: eu-west-1
          aws-secret-access-key: ${{ secrets.ACCESS_KEY_SECRET }}
      - run: yarn --cwd infra
      - uses: pulumi/actions@v3
        with:
          command: preview
          stack-name: verygoodsoftware/dev
          work-dir: infra
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
  up:
    name: Pulumi Up
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs:
      - buildJs
    steps:
      - uses: actions/checkout@v2
      - name: Download Artifacts
        uses: actions/download-artifact@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14.x
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.ACCESS_KEY }}
          aws-region: eu-west-1
          aws-secret-access-key: ${{ secrets.ACCESS_KEY_SECRET }}
      - run: yarn --cwd infra
      - uses: pulumi/actions@v3
        with:
          command: up
          stack-name: verygoodsoftware/dev
          work-dir: infra
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}